# Generated by Django 3.1.1 on 2022-02-03 14:30

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('color', models.CharField(max_length=256, null=True)),
                ('start', models.FloatField(default=0)),
                ('end', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('license', models.CharField(max_length=256)),
                ('ext', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=256)),
                ('results', models.BinaryField(null=True)),
                ('progres', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('D', 'Done'), ('E', 'Error')], default='U', max_length=2)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineSegmentAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.annotation')),
                ('timeline_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.timelinesegment')),
            ],
        ),
        migrations.AddField(
            model_name='timelinesegment',
            name='annotations',
            field=models.ManyToManyField(through='backend.TimelineSegmentAnnotation', to='backend.Annotation'),
        ),
        migrations.AddField(
            model_name='timelinesegment',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.timeline'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.video'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.annotationcategory'),
        ),
    ]
