# Generated by Django 3.1.1 on 2022-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginrun',
            name='results',
        ),
        migrations.RemoveField(
            model_name='pluginrunresult',
            name='data',
        ),
        migrations.AddField(
            model_name='pluginrunresult',
            name='data_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO_DATA'), ('I', 'IMAGE_DATA'), ('S', 'SCALAR_DATA'), ('H', 'HIST_DATA'), ('SH', 'SHOTS_DATA'), ('R', 'RGB_HIST_DATA')], default='S', max_length=2),
        ),
    ]
