# Generated by Django 3.1.1 on 2022-02-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220208_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoanalyse',
            old_name='progres',
            new_name='progress',
        ),
    ]
