# Generated by Django 3.1.1 on 2022-01-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220130_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=256)),
                ('hash_id', models.CharField(max_length=256)),
                ('results', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('D', 'Done'), ('E', 'Error')], default='U', max_length=2)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
    ]
