# Generated by Django 3.1.1 on 2022-06-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_timeline_visualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.timeline'),
        ),
    ]
