# Generated by Django 3.1.1 on 2022-01-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_videoanalyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalyse',
            name='progres',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='videoanalyse',
            name='results',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
