# Generated by Django 3.1.1 on 2022-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_timeline_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='timeline',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='visualization',
            field=models.CharField(choices=[('C', 'COLOR'), ('CC', 'CATEGORYCOLOR'), ('SC', 'SCALARCOLOR'), ('SL', 'SCALARLINE'), ('H', 'HIST')], default='C', max_length=2),
        ),
    ]
