# Generated by Django 3.1.1 on 2022-04-17 16:29

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_auto_20220414_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('type', models.CharField(max_length=256, null=True)),
                ('key', models.CharField(max_length=256, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
        migrations.CreateModel(
            name='ShortcutAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.annotation')),
                ('shortcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.shortcut')),
            ],
        ),
    ]
