# Generated by Django 3.1.1 on 2022-07-28 14:53

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220720_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='color',
            field=models.CharField(default=backend.models.random_color_string, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='annotationcategory',
            name='color',
            field=models.CharField(default=backend.models.random_color_string, max_length=256, null=True),
        ),
    ]
