# Generated by Django 3.1.1 on 2022-02-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220201_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=256)),
                ('timeline_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.timelinesegment')),
            ],
        ),
    ]
