# Generated by Django 3.1.1 on 2022-04-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_shortcut_shortcutannotation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortcutAnnotation',
            new_name='AnnotationShortcut',
        ),
    ]
