# Generated by Django 3.1.1 on 2022-02-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_timeline_timelineannotation_timelinesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='timelinesegment',
            name='end',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='timelinesegment',
            name='start',
            field=models.FloatField(default=0),
        ),
    ]
