# Generated by Django 3.1.1 on 2022-07-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220728_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='color',
            field=models.CharField(default='#FF00FF', max_length=256),
        ),
        migrations.AlterField(
            model_name='annotationcategory',
            name='color',
            field=models.CharField(default='#FF00FF', max_length=256),
        ),
    ]
