# Generated by Django 3.1.1 on 2022-04-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220417_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcut',
            old_name='key',
            new_name='keys',
        ),
    ]
