# Generated by Django 3.1.1 on 2022-08-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20220728_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='color_map',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pluginrun',
            name='status',
            field=models.CharField(choices=[('U', 'UNKNOWN'), ('E', 'ERROR'), ('D', 'DONE'), ('R', 'RUNNING'), ('Q', 'QUEUED'), ('W', 'WAITING')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='visualization',
            field=models.CharField(choices=[('C', 'COLOR'), ('CC', 'CATEGORY_COLOR'), ('SC', 'SCALAR_COLOR'), ('SL', 'SCALAR_LINE'), ('H', 'HIST')], default='C', max_length=2),
        ),
    ]
