# Generated by Django 3.1.1 on 2022-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20220419_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='keys_string',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
