# Generated by Django 3.1.1 on 2022-05-03 11:22

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_shortcut_keys_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='type',
        ),
        migrations.CreateModel(
            name='VideoAnalyseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('data', models.BinaryField(null=True)),
                ('type', models.CharField(choices=[('V', 'VIDEO_DATA'), ('I', 'IMAGE_DATA'), ('S', 'SCALAR_DATA'), ('H', 'HIST_DATA')], default='S', max_length=2)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.videoanalyse')),
            ],
        ),
        migrations.AddField(
            model_name='timeline',
            name='video_analyse_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.videoanalyseresult'),
        ),
    ]
