# Generated by Django 3.1.1 on 2022-08-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20220815_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='color_map',
            new_name='colormap',
        ),
    ]
