# Generated by Django 3.1.1 on 2023-02-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20220815_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrun',
            name='in_scheduler',
            field=models.BooleanField(default=False),
        ),
    ]
