# Generated by Django 3.1.1 on 2022-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20220503_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='type',
            field=models.CharField(choices=[('A', 'ANNOTATION'), ('R', 'VIDEO_ANALYSE_RESULT')], default='A', max_length=2),
        ),
    ]
