# Generated by Django 3.1.1 on 2023-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_pluginrun_in_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
