# Generated by Django 3.1.1 on 2022-05-03 13:04

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_timeline_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=backend.models.gen_hash_id, max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='VideoAnalyse',
            new_name='PluginRun',
        ),
        migrations.RenameModel(
            old_name='VideoAnalyseResult',
            new_name='PluginRunResult',
        ),
        migrations.DeleteModel(
            name='TimelineAnalyse',
        ),
    ]
