# Generated by Django 3.1.1 on 2022-05-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20220503_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pluginrunresult',
            old_name='video',
            new_name='plugin_run',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='video_analyse_result',
            new_name='plugin_run_result',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='type',
            field=models.CharField(choices=[('A', 'ANNOTATION'), ('R', 'PLUGIN_RESULT')], default='A', max_length=2),
        ),
    ]
