# Generated by Django 3.1.1 on 2023-06-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20230607_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
