# Generated by Django 3.1.1 on 2023-06-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_tibavauser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tibavauser',
            managers=[
            ],
        ),
    ]
