# Generated by Django 3.1.1 on 2023-06-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20230623_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibavauser',
            name='video_max_size',
            field=models.IntegerField(default=52428800),
        ),
    ]
