# Generated by Django 3.1.1 on 2023-06-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_tibavauser_video_max_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tibavauser',
            old_name='video_max_size',
            new_name='max_video_size',
        ),
    ]
