# Generated by Django 3.1.1 on 2024-02-19 11:34

from django.db import migrations, models
import django.db.models.deletion


def remove_cluster_items_flagged_deleted(apps, schema_editor):
    ClusterItem = apps.get_model('backend', 'ClusterItem')
    ClusterItem.objects.filter(deleted=True).delete()

def populate_cluster_item_fields(apps, schema_editor):
    from analyser.data import DataManager

    ClusterItem = apps.get_model('backend', 'ClusterItem')
    data_manager = DataManager('/predictions')
    for item in ClusterItem.objects.all():
        data = data_manager.load(item.plugin_run_result.data_id)
        with data:
            data.load()
        for cluster in data.clusters:
            if cluster.id == item.cluster_timeline_item.cluster_id:
                break
        item.embedding_id = cluster.embedding_ids[item.embedding_index]
        if item.embedding_id in cluster.sample_embedding_ids:
            item.is_sample = True

        image_id =  item.image_path.split('/')[-1].removesuffix('.jpg')

        run_result = (item.plugin_run_result
                          .plugin_run
                          .results
                          .filter(type='I')
                          .first())
        data = data_manager.load(run_result.data_id)
        with data:
            data.load()
        for image in data.images:
            if image.id == image_id:
                item.time = image.time
                item.delta_time = image.delta_time
                break

        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20240215_0910'),
    ]

    operations = [
        migrations.RunPython(remove_cluster_items_flagged_deleted, migrations.RunPython.noop),
        migrations.AddField(
            model_name='clusteritem',
            name='delta_time',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusteritem',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clusteritem',
            name='time',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clusteritem',
            name='cluster_timeline_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.clustertimelineitem'),
        ),
        migrations.RemoveField(
            model_name='clusteritem',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='type',
            field=models.CharField(choices=[('A', 'ANNOTATION'), ('R', 'PLUGIN_RESULT'), ('T', 'TRANSCRIPT')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='clusteritem',
            name='embedding_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pluginrunresult',
            name='plugin_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='backend.pluginrun'),
        ),
        migrations.RunPython(populate_cluster_item_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='clusteritem',
            name='embedding_index',
        ),
    ]
