# Generated by Django 3.1.1 on 2023-06-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20230625_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibavauser',
            name='allowance',
            field=models.IntegerField(default=3),
        ),
    ]
